In [ ]:
import numpy as np

In [ ]:
my_list=[1,2,3,4,5]

In [ ]:

np_array_list=np.array(my_list)
np_array_list
#Convert a normal Python list into a NumPy array.

array([1, 2, 3, 4, 5])

In [ ]:
#Creating numpy array using arange built-in function
my_list = np.arange(10)
my_list
my_list = np.arange(0,10)
my_list


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_list_1=np.arange(0,20,2)
my_list_1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
my_list_0=np.zeros(10)
my_list_0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]
matrix
np_matrix=np.array(matrix)
np_matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np_matrix.size

9

In [ ]:
np_matrix.shape

(3, 3)

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[2:9:3]

array([2, 5, 8])

In [ ]:
#Numerical operations
sample_array=[1,2,3,4,5,6]
a=np.array(sample_array)
a


array([1, 2, 3, 4, 5, 6])

In [ ]:
sum=a+1
sum

array([2, 3, 4, 5, 6, 7])

In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])

In [ ]:
a+b

array([ 6,  8, 10, 12, 14])

In [ ]:
a-b

array([-4, -4, -4, -4, -4])

In [ ]:
a*b

array([ 5, 12, 21, 32, 45])

In [ ]:
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       , 0.55555556])

In [ ]:
c = np.ones((3, 3))
c*3

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.dot(b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving populations.txt to populations.txt


In [ ]:
data = np.loadtxt('populations.txt')
year, hares, lynxes, carrots = data.T
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [ ]:
np.argmax(data,axis=0)

array([20,  3,  4,  0])

In [ ]:
sum=np.sum(data,axis=0)
sum

In [ ]:
np.mean(data,axis=0)

array([ 1910.        , 34080.95238095, 20166.66666667, 42400.        ])

In [ ]:
np.std(data,axis=0)

array([6.05530071e+00, 2.08979065e+04, 1.62545915e+04, 3.32250623e+03])

In [ ]:
#Broadcasting

arr = np.array([[1,2,3],
                [4,5,6]])

print(arr + 10)

[[11 12 13]
 [14 15 16]]


In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

# Add v to each row of x using broadcasting
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]
